### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NEROSIUS** [namkazt/sd-webui-prompt-history#27]
This may help many people.

1. History page number input:  So the user has an option other than the Prev & Next

2. Gallery View :  User than hover over the pics and have something like a [Lightbox] popout hovering

3. Export option: Not sure if already have this feature or workaround. From time to time the Web-UI A1111 crashes and needs to be reinstalled, but would like to have all the history migrated to new fresh install.

Your extension is very useful and make working more efficient....Thank you for creating this.

**Comment by illuculent** [comment]
History page number input: So the user has an option other than the Prev & Next. This should be an easy addition to add. I have over 250 pages and I need to replicate something from ~100. Currently one has to click Next over 100 times to get there. With a slow page refresh due to the thumbnails, this takes quite some time to accomplish. An input box with a page reference that allows us to jump to that page would be most helpful. BTW, IMHO, this is one of the best plugins made for Auto1111 especially since they upgraded and removed the useful capabilities from the styles feature. TIA

**Comment by namkazt** [comment]
yes, it is a nice feature to have, i will add it soon.

**Comment by namkazt** [comment]
option 3: f257acff8ed495fa9ed7161a1f63e232a6276154

**Comment by namkazt** [comment]
option 1: dad4e4568824f888484d03b11d1ee6b5c367f0c0

option 2: not planned
